source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.4’
use_frameworks!
target ‘MyFirstGPUImage’ do
  pod ‘GPUImage'
  pod 'SnapKit'
  pod 'FLEX', '~> 2.0', :configurations => ['Debug']
  pod 'ProgressHUD'
end

